const webProjects = [
  {
    project: "project 1",
    img: "/project_imgs/cd-package-design-x-1.jpg",
    relevance: true,
    type: "trailers",
    id: 1,
  },
  {
    project: "project 2",
    img: "/project_imgs/cd-package-design-x-2.jpg",
    relevance: false,
    type: "films",
    id: 2,
  },
  {
    project: "project 3",
    img: "/project_imgs/cd-package-design-x-3.jpg",
    relevance: true,
    type: "ads",
    id: 3,
  },
  {
    project: "project 4",
    img: "/project_imgs/cd-package-design-x-4.jpg",
    relevance: false,
    type: "animation",
    id: 4,
  },
  {
    project: "project 5",
    img: "/project_imgs/cd-package-design-x-5.jpg",
    relevance: true,
    type: "branding",
    id: 5,
  },
  {
    project: "project 6",
    img: "/project_imgs/cd-package-design-x-6.jpg",
    relevance: false,
    type: "vfx",
    id: 6,
  },
  {
    project: "project 7",
    img: "/project_imgs/cd-package-design-x-7.jpg",
    relevance: true,
    type: "trailers",
    id: 7,
  },
  {
    project: "project 8",
    img: "/project_imgs/cd-package-design-x-8.jpg",
    relevance: false,
    type: "films",
    id: 8,
  },
  {
    project: "project 9",
    img: "/project_imgs/cd-package-design-x-9.jpg",
    relevance: true,
    type: "ads",
    id: 9,
  },
  {
    project: "project 10",
    img: "/project_imgs/cd-package-design-x-10.jpg",
    relevance: false,
    type: "animation",
    id: 10,
  },
  {
    project: "project 11",
    img: "/project_imgs/cd-package-design-x-11.jpg",
    relevance: true,
    type: "branding",
    id: 11,
  },
  {
    project: "project 12",
    img: "/project_imgs/cd-package-design-x-12.jpg",
    relevance: false,
    type: "vfx",
    id: 12,
  },
  {
    project: "project 13",
    img: "/project_imgs/cd-package-design-x-13.jpg",
    relevance: true,
    type: "trailers",
    id: 13,
  },
  {
    project: "project 14",
    img: "/project_imgs/cd-package-design-x-14.jpg",
    relevance: true,
    type: "films",
    id: 14,
  },
];

export default webProjects;
